# Generated by Django 2.2 on 2019-04-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('inventory_count', models.IntegerField()),
            ],
        ),
    ]
